services:
  - type: web
    name: surigao-runners
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn surigao_runners.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: surigao_runners.settings
      - key: PYTHON_VERSION
        value: 3.12