# Generated by Django 5.2 on 2025-05-03 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_event_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='distance',
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='registration.event')),
            ],
        ),
        migrations.AddField(
            model_name='runner',
            name='distance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registration.distance'),
            preserve_default=False,
        ),
    ]
