# Generated by Django 5.2 on 2025-05-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_event_distance_distance_runner_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
