# Generated by Django 5.2 on 2025-05-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_runner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
