# Generated by Django 5.2 on 2025-05-17 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_runner_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
