# Generated by Django 5.1.6 on 2025-06-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_runner_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='label',
            field=models.CharField(max_length=10),
        ),
    ]
