# Generated by Django 5.1.6 on 2025-06-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_distance_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='name',
        ),
        migrations.AddField(
            model_name='runner',
            name='first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='First Name (with middle initial/name)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runner',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
