# Generated by Django 5.1.6 on 2025-06-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_remove_runner_name_runner_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='bib_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
