# Generated by Django 5.1.6 on 2025-06-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_runner_bib_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
