# Generated by Django 5.1.6 on 2025-06-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_runner_registration_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='registration_deadline',
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
