# Generated by Django 5.2 on 2025-05-03 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='gcash_ref_number',
        ),
        migrations.RemoveField(
            model_name='runner',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(default='urelchua85@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runner',
            name='age',
            field=models.PositiveIntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runner',
            name='emergency_contact_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runner',
            name='emergency_contact_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runner',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runner',
            name='shirt_size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runner',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event'),
        ),
    ]
