# Generated by Django 5.2 on 2025-05-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_runner_gcash_ref_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_verified',
        ),
    ]
